# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import text_summarizer_pb2 as text__summarizer__pb2


class TextSummarizerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Summarize = channel.unary_unary(
                '/TextSummarizer/Summarize',
                request_serializer=text__summarizer__pb2.SummarizeRequest.SerializeToString,
                response_deserializer=text__summarizer__pb2.SummarizeResponse.FromString,
                )


class TextSummarizerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Summarize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TextSummarizerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Summarize': grpc.unary_unary_rpc_method_handler(
                    servicer.Summarize,
                    request_deserializer=text__summarizer__pb2.SummarizeRequest.FromString,
                    response_serializer=text__summarizer__pb2.SummarizeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TextSummarizer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TextSummarizer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Summarize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TextSummarizer/Summarize',
            text__summarizer__pb2.SummarizeRequest.SerializeToString,
            text__summarizer__pb2.SummarizeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
