# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: text_summarizer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15text_summarizer.proto\"4\n\x10SummarizeRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x12\n\nmax_length\x18\x02 \x01(\x05\"$\n\x11SummarizeResponse\x12\x0f\n\x07summary\x18\x01 \x01(\t2D\n\x0eTextSummarizer\x12\x32\n\tSummarize\x12\x11.SummarizeRequest\x1a\x12.SummarizeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'text_summarizer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_SUMMARIZEREQUEST']._serialized_start=25
  _globals['_SUMMARIZEREQUEST']._serialized_end=77
  _globals['_SUMMARIZERESPONSE']._serialized_start=79
  _globals['_SUMMARIZERESPONSE']._serialized_end=115
  _globals['_TEXTSUMMARIZER']._serialized_start=117
  _globals['_TEXTSUMMARIZER']._serialized_end=185
# @@protoc_insertion_point(module_scope)
